services:
    oxpus.sam.controller:
        class: oxpus\sam\controller\main
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%core.table_prefix%'
            - '@service_container'
            - '@ext.manager'
            - '@path_helper'
            - '@dbal.conn'
            - '@config'
            - '@log'
            - '@controller.helper'
            - '@auth'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
    oxpus.sam.listener:
        class: oxpus\sam\event\main_listener
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%core.table_prefix%'
            - '@ext.manager'
            - '@path_helper'
            - '@service_container'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@template'
            - '@user'
            - '@language'
        tags:
            - { name: event.listener }
